# Generated by Django 3.1 on 2020-08-14 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0002_pessoa_idade'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='escolaridade',
            field=models.CharField(choices=[('NI', 'Não informado'), ('EF', 'Ensino Fundamental'), ('EM', 'Ensino Médio'), ('ES', 'Ensino Superior')], default='NI', max_length=2),
        ),
    ]
