# Generated by Django 3.1 on 2020-08-14 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0005_pessoa_depto_atual'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='hist_deptos',
            field=models.ManyToManyField(related_name='hist_pessoa_depto', to='aplicacao.Departamento'),
        ),
    ]
